### PR TITLE
docs: fixup the readme

### PR DESCRIPTION
**Pull request by posborne**
Signed-off-by: Paul Osborne <osbpau@gmail.com>

### CODE REVIEW

**Comment by posborne** [comment]
Resolves #9

**Comment by nastevens** [comment]
Dumb question - do you have a homu instance running that I should actually respond appropriately, or was the `r?` just a convenience?

**Comment by posborne** [comment]
Yes, homu is running!

**Comment by nastevens** [comment]
r+

**Comment by nastevens** [comment]
@homu r+

**Comment by nastevens** [comment]
Sweet! That is awesome!

**Pull request merged**
