### PR TITLE
Several updates

### LINKED ISSUE #56: outdated docs
The docs at http://rust-embedded.github.io/rust-i2cdev which https://crates.io/crates/i2cdev links is outdated.

Either these should be kept in sync with the latest version or https://crates.io/crates/i2cdev should link to an alternative: https://docs.rs/i2cdev

### PR DESCRIPTION
**Pull request by eldruin**
Including:
- Update `nix`
- Raise MSRV to 1.46.0 due to dependencies. Effectively it has been raised already and so far nobody noticed.
- Fix warnings
- Improvements to `Cargo.toml`
- Add bors configuration
- Switch to GHA for CI (tested on my fork)

Fixes #56

### CODE REVIEW

**Review by ryankurte — APPROVED** [review]
lgtm, thanks! lets see how CI fares...

bors r+

**Comment by eldruin** [comment]
One of the names for bors must be wrong but I do not know which one.
bors retry

**Comment by eldruin** [comment]
bors try

**Comment by ryankurte** [comment]
:+1: 

bors r+

**Pull request merged**
