### PR TITLE
ci: enable rust-embedded-bot

### PR DESCRIPTION
**Pull request by posborne**
CC @nastevens

### CODE REVIEW

**Comment by nastevens** [comment]
@rust-embedded-bot r+

**Comment by nastevens** [comment]
@rust-embedded-bot r-

**Comment by nastevens** [comment]
I tried to make the easy fix and bump bitflags to 0.6.0 (since 0.5.0 fails in Rust 1.7), but 0.6.0 apparently breaks almost everything. Ninja rebase and it never happened....

**Comment by nastevens** [comment]
Weird, I wonder what was up with the failures before. Oh well.

@rust-embedded-bot r+

**Comment by nastevens** [comment]
@rust-embedded-bot r=nastevens

**Comment by posborne** [comment]
@rust-embedded-bot r-

**Comment by posborne** [comment]
@rust-embedded-bot r=nastevens

**Comment by posborne** [comment]
:tada:

**Pull request merged**
