### PR TITLE
added smbus_read_i2c_block_data

### PR DESCRIPTION
**Pull request by Ragnaroek**

### CODE REVIEW

**Comment by posborne** [comment]
@Ragnaroek Please take a look at the CI failure.  Some of the ones on older versions of Rust we might just bump the minimum supported version (related to changes in deps), but it does look like there is some work to do in the mocks for recent versions of rust.

**Comment by posborne** [comment]
Other than that, change looks good.  Names of the constants are somewhat confusing in the kernel, but it is probably better to match that than to do something else.

**Comment by Ragnaroek** [comment]
builds now. this PR drops support for all but the recent version of rust

**Comment by posborne** [comment]
Thanks I may revisit adding back some older versions depending on my needs or if anyone complains.  For now, however, this works for me.

**Comment by Ragnaroek** [comment]
Can you also update the build on crates.io, I could then get rid of my fork dependency :)

**Comment by posborne** [comment]
> Can you also update the build on crates.io, I could then get rid of my fork dependency :)

0.3.1 is now published: https://crates.io/crates/i2cdev

**Pull request merged**
