### PR TITLE
bump nix to 0.14 to fix libc issues

### PR DESCRIPTION
**Pull request by ryankurte**
~Waiting on: https://github.com/nix-rust/nix/issues/1060#issuecomment-494627579~
See also: https://github.com/rust-embedded/linux-embedded-hal/pull/17
Patching up to git source tested to be working

### CODE REVIEW

**Comment by juliangaal** [comment]
FYI: solution suggested [here](https://github.com/nix-rust/nix/issues/1057#event-2356640839) may not work. 
This should fix the issue, until this pr is not merged 
```toml
[patch.crates-io]
i2cdev = { git = "https://github.com/ryankurte/rust-i2cdev" }
```

**Comment by ryankurte** [comment]
@posborne  nix 0.14.x has landed and IC seems happy ^_^

**Comment by drinkdhmo** [comment]
Should the version number also be bumped to 0.4.2?

**Comment by posborne** [comment]
This project hasn't been updated to declare and test against a MSRV formally (https://github.com/rust-embedded/wg/blob/master/ops/msrv.md).  I believe from 0.11 -> 0.14 of nix certainly would change the implicit MSRV which would warrant a "major" version bump (0.4 -> 0.5) as I understand it.

It certainly seems annoying to have a major bump for this but this crate does have decent fan-in from other published crates and I am hesitant to possibly break the MSRV of other crates and projects so I believe the correct change here is to go to 0.5 with an MSRV for the new version of 1.24.1 based on the nix MSRV @ 0.14.

**Comment by posborne** [comment]
I'm willing to go with the MSRV from sysfs-gpio of 1.26.0 as the "implied" MSRV right now.  The MSRV for nix is 1.24.1 for 0.14 so I think this is OK.

**Pull request merged**
