### PR TITLE
BMP180 pressure and temp sensor support.

### PR DESCRIPTION
**Pull request by MrSpock**
Hi,
I needed support for BMP180 and I needed to lear Rust. Here is result :)
Tested on my real BMP180 against other library (same results) and test scenario based on BMP180 documentation.

### CODE REVIEW

**Comment by Kixunil** [comment]
I'm afraid you missed #27. But shouldn't be much of a problem.

**Comment by MrSpock** [comment]
Yes, definitely I missed that one :) Single file so yes - no problem to extract that to separate crate.

**Comment by posborne** [comment]
Awesome, thanks for the contribution.  Been busy lately, but hoping to get back to being a better maintainer here or adding other maintainers that will be able to drive things more actively.

**Comment by tadeegan** [comment]
Did you ever extract this to its own crate? I'm interested in using it :D.

**Comment by Kixunil** [comment]
As I wrote in #27, I've started [working on it](https://github.com/Kixunil/i2cdev-sensors).

What needs to be done:

- [ ] Decide where to put the sensor traits (`Thermometer`, `Accelerometer`...)
- [ ] Create and publish the crate for the traits
- [ ] Who should be the owner (of crates, repo)?
- [ ] Licenses
- [ ] Fill info into `Cargo.toml` for each sensor and publish them.
- [ ] Merge #28

**Comment by posborne** [comment]
Closing this as we are moving away from adding additional sensors/traits to this crate in favor of building those on top of embedded-hal traits.

**Pull request closed without merging**
