### PR TITLE
Removed sensors, so they can be put in separate crate

### LINKED ISSUE #27: Separate sensors into other crate
I believe that sensors are higher-level stuff, which should use i2c crate as their dependency. It makes little sense to pull also code for sensors if somebody wants to use just i2c.

BTW, regarding this issue and the others I filled, I'm willing to help with code, if you agree. I already have some code (open and io traits). (I didn't realize that I2C library already exists when I was writing it.)

### PR DESCRIPTION
**Pull request by Kixunil**
Fixes #27

### CODE REVIEW

**Comment by nastevens** [comment]
Prior to merging this, the code that has been deleted should first be moved to a new repo. Is this something that we want to create in rust-embedded? Or something that would maybe make sense in someone's personal github area? I don't know that it makes much sense in rust-embedded. Are these libraries something that you want to keep maintaining @posborne?

**Comment by posborne** [comment]
I'm fine with maintaining them to some degree.  Since individual drivers are pretty small, I wonder if it might make sense to have a single repo with several drivers (possibly not just i2c drivers).  Each driver would still be its own crate.

I feel this might help with driver maintainability/etc. as we get some scale and infrastructure reuse.  Thoughts?

**Comment by Kixunil** [comment]
I agree that putting drivers in single repo is fine if they are small. Especially, if each of them will be separate crate. `rust-embedded/rust-device-drivers` sounds good to me.

**Comment by tafia** [comment]
I also agree for a separate crate. 
What about traits management? Do we need a dedicated repo to handle them all as well (out of i2c)?

**Comment by posborne** [comment]
> What about traits management? Do we need a dedicated repo to handle them all as well (out of i2c)?

I don't know on a final location as of yet, but we have been tossing around a few ideas for sync/async traits for doing I2C and other interfacing here: https://github.com/rust-embedded/rfcs/issues/19

**Comment by tafia** [comment]
Thanks!

**Comment by posborne** [comment]
I'm going to close this as it is a little out of date now that we have a more clear path forward for defining things on top of the embedded-hal traits.  I still think there might be a place for an umbrella project that maintains multiple sensor crates in a single repository but it probably shouldn't be this repository as it is very tightly coupled to Linux and, ideally, device drivers would have minimal dependencies and be able to work on a `no-std` environment to support a wide variety of host operating environments.

**Pull request closed without merging**
